version: '3.1'

services:
  nginx:
    build: .
    volumes:
      - ./src/nginx/:/etc/nginx/conf.d
    ports:
      - 8000:80
    environment:
      - REDIS=redis
    depends_on:
      - redis

  redis:
    image: redis
