version: '3'

services:
  nginx:
    build: .
    ports:
      - 443:443
    environment:
      - REDIS=redis
      - AUTH_CENTER=http://auth_center
      - WEB_BACKEND=http://web_backend

    links:
      - auth_center
      - redis
      - web_backend

    depends_on:
      - redis
      - web_backend
      - auth_center

  redis:
    image: redis
    ports:
      - 6379:6379

  auth_center:
    container_name: auth_center
    build:
      context: .
      dockerfile: docker/aiohttp-start.Dockerfile

    command: python mockserver/auth_center.py

    links:
      - redis

    ports:
      - 8001:80

  web_backend:
    container_name: web_backend
    build:
      context: .
      dockerfile: docker/aiohttp-start.Dockerfile

    ports:
      - 8002:80

    command: python mockserver/web_backend.py
