FROM openresty/openresty

ENV openresty /usr/local/openresty
ENV JWT_KEY -----BEGIN CERTIFICATE-----MIIDpjCCAo4CCQC1AeRCsIyFljANBgkqhkiG9w0BAQsFADCBlDELMAkGA1UEBhMCUlUxDzANBgNVBAgMBk1vc2NvdzELMAkGA1UEBwwCUlUxHDAaBgNVBAoME0JhcnlzaG5pa292IE5pa29sYXkxEzARBgNVBAsMCm5naW54LWF1dGgxEzARBgNVBAMMCm5naW54LWF1dGgxHzAdBgkqhkiG9w0BCQEWEGFkbWluQG5naW54LWF1dGgwHhcNMTkwNDI4MjAzNTIxWhcNMjAwNDI3MjAzNTIxWjCBlDELMAkGA1UEBhMCUlUxDzANBgNVBAgMBk1vc2NvdzELMAkGA1UEBwwCUlUxHDAaBgNVBAoME0JhcnlzaG5pa292IE5pa29sYXkxEzARBgNVBAsMCm5naW54LWF1dGgxEzARBgNVBAMMCm5naW54LWF1dGgxHzAdBgkqhkiG9w0BCQEWEGFkbWluQG5naW54LWF1dGgwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDtIWKIuU/t00MIa+joGZLn6RuI1SCMjNn3kB8SFFsbPnWyqHdy0nNbHCTMlq/+Vzra1k3nE9/MLlRqEwypq1oUNrh/ISD24Djfgrmzlmf6/CL4gpTghWjMPhySxfn+V4FDU5SCG6ci+ZqnByPYSgF9Yl2V6124a2tvsy0DeA03pDYkzhc+86+wvQeJ+KweOctE7EARGLjy85yFZCOg2A8hocwSQxur7QZBHxUv8RwWXZ6FffXX/uTOlOnbU/VRRjwE4o1E2j7qrXHHVnyqMbCcETmIdk+yPfoEOx7DbSRjXTdnVwWmEPC1aqd7CYfgbvNA5GjbQU8rG3UgfGefLW4XAgMBAAEwDQYJKoZIhvcNAQELBQADggEBANzlJERPSfV24nf1I4jjnMGimm/hC/JDw2vG7F3CQo/nZ2jKQlNvRZMb8J8SvWgi9USqipX29jkPmyyMLrOv0vgIcVB57ZTeYlMNUM8EdxnQLt8FE87gqlAuTSwNm0z/b5oxGDnajA/RwTkUQTgSWgbVhY+VNunzZizkvo3qwo0ipGI0MntIfmydDRwL2ydo4nZlSpzymOMHL0qVJgrsP9q+rOdZuK/6KpYIK/o2QGUpgYjiZPk24QMAIw3gliYiXbqHnHdcq+Hsv41w1aphJBWxjMckw70NWN7wENi2wzzpzHbCJyyalM78OrGaj7Ku6QS/O9tk39PNk6iKjY1t7LA=-----END CERTIFICATE-----


COPY ssl/nginx-auth.key /etc/ssl/private/nginx-auth.key
COPY ssl/nginx-auth.crt /etc/ssl/certs/nginx-auth.crt
COPY ssl/nginx-auth.pem /etc/ssl/certs/nginx-auth.pem

COPY src/nginx/nginx.nginx ${openresty}/nginx/conf/nginx.conf
COPY src/nginx/ssl.nginx ${openresty}/nginx/conf/ssl.nginx
COPY src/nginx/proxy_params.nginx ${openresty}/nginx/conf/proxy_params

COPY src/nginx/conf.d /etc/nginx/conf.d/

COPY src/vendor/ ${openresty}/lualib/
COPY src/lua ${openresty}/lualib/

EXPOSE 443